# Adapted from https://github.com/numba/numba/blob/master/azure-pipelines.yml
jobs:
- job: 'Docs'
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 90
  steps:
  - script: |
      echo '##vso[task.setvariable variable=ENV_FILE]environment.yml'
      echo '##vso[task.prependpath]$(HOME)/miniconda3/bin'
    displayName: 'Setting environment variables'

  - script: |
      sudo apt-get install -y libc6-dev-i386
      ci/setup_env.sh
    displayName: 'Setup environment and build pandas'

  - script: |
      source activate pandas-docs
      # Next we should simply have `doc/make.py --warnings-are-errors`, everything else is required because the ipython directive doesn't fail the build on errors (https://github.com/ipython/ipython/issues/11547)
      cd doc/
      make html
    displayName: 'Build documentation'
